Cowpokes_Drone_Cones/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dronecones/', include('drone_cones.urls')),
    # path('accounts/', include("django.contrib.auth.urls")),
]

drone_cones/urls.py
from django.conf import settings
from django.urls import path, include
from . import views

app_name = 'drone_cones'
urlpatterns = [
    # path('login/', views.LoginView.login, name='login'),
    path('home/', views.UserView.user_dash, name='home'),
    path('', views.UserView.user_dash, name='home'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('logout/', views.LoginView.redirect_view, name='redirect'),
    path('order/', views.OrderView.order_page, name='order'),
    path('drones/', views.DroneView.drone_dash, name='drones'),
    path('drones/edit_drone/<int:drone_id>', views.DroneView.edit_drone, name='edit_drone'),
    path('drones/drone_breakdown/<int:drone_id>', views.DroneView.drone_breakdown, name='drone_breakdown'),
    path('account/', views.UserView.account_page, name='account'),
    path('edit_account/', views.UserView.edit_account, name='edit_account'),
    path('edit_address/', views.UserView.edit_address, name='edit_address'),
    path('drone_register', views.DroneView.drone_register, name='drone_register'),
    path('create_account', views.LoginView.create_account, name='create_account'),
    path('order_confirmation', views.OrderView.order_confirmation, name='order_confirmation'),
    ## ADMIN PAGE IS OBSOLETE! DELETE BEFORE RELEASE ###
    path('admin_page', views.AdminView.admin_dash, name='admin_page'),
    ## END COMMENT ##
    path('add_drone', views.addDrone, name='add_drone'),
    path('add_order', views.addOrder, name='add_order'),
    path('manager/', views.ManagerView.manager_dash, name='manager'),
    path('manager/users/', views.ManagerView.view_users, name='all_users'),
    path('manager/finance/', views.ManagerView.view_finances, name='finance'),
    path('manager/stock/', views.ManagerView.view_stock, name='stock'),
    path('manager/all_drones/', views.ManagerView.view_drones, name='all_drones'),
    path('manager/users/edit_user/<int:account_id>', views.ManagerView.edit_user, name="edit_user"),
    path('manager/all_drones/edit_drone/<int:drone_id>', views.ManagerView.edit_drone, name="edit_drone_manager"),
    path('manager/all_drones/drone_breakdown/<int:drone_id>', views.ManagerView.drone_breakdown, name="drone_breakdown"),
    path('manager/stock/edit_stock/<int:product_id>', views.ManagerView.edit_stock, name="edit_stock"),
    path('get_products/', views.OrderView.get_products, name='get_products'),
    path('add_to_cart/', views.OrderView.add_to_cart, name='add_to_cart'),
    path('send_order/', views.OrderView.send_order, name='send_order'),
    path('remove_from_order/', views.OrderView.remove_from_order, name='remove_from_order'),
    path('get_account_address/', views.OrderView.get_account_address, name='get_account_address'),
]

drone_cones/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from drone_cones.models import *
import json


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=46, required=True, help_text='Enter your unique username.')
    first_name = forms.CharField(max_length=46, required=True)
    last_name = forms.CharField(max_length=46, required=True)
    email = forms.EmailField(max_length=254, required=True, help_text='Input a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1')

class DroneRegisterForm(forms.Form):
    drone_name = forms.CharField(label="drone_name", max_length = 100)
    drone_size = forms.CharField(label="drone_size", max_length = 100)

class OrderForm(forms.Form):
    #items = forms.CharField(label = "items", max_length=1024)
    address = forms.CharField(label = "address", max_length=30)
    address2 = forms.CharField(label = "address2", max_length=30, required=False)
    city = forms.CharField(label = "city", max_length=30)
    state = forms.CharField(label = "state", max_length=30)
    zip = forms.IntegerField(label = "zip")
    timeOrdered = models.TimeField()
    timeDelivered = models.TimeField()
    timeToDeliver = models.TimeField()

class EditAccountForm(forms.Form):
    username = forms.CharField(label = "username", max_length=100)
    first_name = forms.CharField(label = "first_name", max_length=100)
    last_name = forms.CharField(label = "last_name", max_length=100)

class EditAddressForm(forms.Form):
    address_1 = forms.CharField(label="address_1", max_length = 100)
    address_2 = forms.CharField(label="address_2", max_length = 100, required=False)
    city = forms.CharField(label="city", max_length = 100)
    state = forms.CharField(label="state", max_length=100)
    zip = forms.CharField(label="zip", max_length = 100)

class EditDroneForm(forms.Form):
    drone_name = forms.CharField(label="drone_name", max_length = 100)
    drone_size = forms.CharField(label="drone_size", max_length = 100)
    is_active = forms.BooleanField(label="is_active", required=False)

class EditUserManagerForm(forms.Form):
    username = forms.CharField(label="username", max_length=100)
    first_name = forms.CharField(label="first_name", max_length=100)
    last_name = forms.CharField(label="last_name", max_length=100)
    is_manager = forms.BooleanField(label="is_manager", required=False)

class EditStock(forms.Form):
    stockAvailable = forms.IntegerField(label="stockAvailable")

drone_cones/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseForbidden, HttpResponseNotAllowed
from drone_cones.models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.dispatch import receiver
from django.db.models.signals import post_save
from drone_cones.core.forms import SignUpForm, OrderForm
from django.shortcuts import redirect
from datetime import date, datetime, timedelta
from drone_cones.core.forms import *
import json
from django.shortcuts import render
from drone_cones.models import Products, Drone
from django.utils import timezone
from random import randint


def addDrone(request):

    user = request.user
    account = Account.objects.get(user=user)


    if request.method == 'POST':
        
        form = DroneRegisterForm(request.POST)

        if form.is_valid():

            drone_name = form.cleaned_data.get('drone_name')
            drone_size = form.cleaned_data.get('drone_size')

            if drone_size == "Large":
                drone_scoops = 10

            elif drone_size == "Medium":
                drone_scoops = "7"

            elif drone_size == "Small":
                drone_scoops = "5"

            else:
                return HttpResponseNotAllowed()

            account.drone_set.create(droneName = drone_name, size = drone_size, scoops = drone_scoops, isActive = True, dateRegistered=date.today())

            response = redirect("drone_cones/drones/")

            return HttpResponseRedirect("drones")

def addOrder(request):
    user = request.user
    associated_account = Account.objects.get(user=user)

    context = {'form': OrderForm(), 'account': associated_account}

    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            form.save()
            account_id = associated_account.Id
            address = form.cleaned_data['address']
            address2 = form.cleaned_data['address2']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            zip_code = form.cleaned_data['zip']

            # Get selected flavor from the JavaScript
            selected_flavor1 = request.POST.get('items', '')

            # Process the selected flavor as needed

            drone = form.cleaned_data['drone']

            # _______________________
            # | SELECTING DRONE      |
            # |----------------------|
            # |______________________|

            drone_set = Drone.objects.all()
            
            


            time_ordered = datetime.now()

            timeToDeliver = (datetime.min + timedelta(minutes=10)).time()

            timeDelivered = time_ordered + timedelta(minutes=10)


            # Save the order to the database
            order = Orders.objects.create(
                account_id = account_id,
                address=address,
                address2=address2,
                city=city,
                state=state,
                zip=zip_code,
                items=order,  # Store selected flavor in JSONField
                drone=drone,
                timeOrdered=time_ordered,
                timeDelivered = timeDelivered,
                timeToDeliver = timeToDeliver,
                # Add other fields as needed
            )

            order.save()


            return render(request, 'drone_cones/confirmation_page.html', context)
        else:
            return render(request, 'drone_cones/order_page.html', context)

    return render(request, 'drone_cones/order_page.html', context)

def droneRegister(request):    
    user = request.user
    associated_account = Account.objects.get(user=user)
    return render(request, "drone_cones/drone_register_page.html", {'account':associated_account})

class LoginView:
    def login(request):
        return render(request, 'drone_cones/login_page.html')

    def redirect_view(request):
        response = redirect('/dronecones/accounts/logout/')
        return response
        
    def create_account(request):
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                firstname = form.cleaned_data.get('first_name')
                lastname = form.cleaned_data.get('last_name')
                email = form.cleaned_data.get('email')
                user = authenticate(username=username, password=raw_password)
                user_account = Account(user=user, firstName=firstname, lastName=lastname, email=email, is_admin = False)

                user_account.save()

                login(request, user=user)
                return redirect('/dronecones/home/')
        else:
            form = SignUpForm()
        return render(request, "drone_cones/create_account_page.html", {'form': form})

class UserView:
    @login_required
    def user_dash(request):
        user = request.user
        associated_account = Account.objects.get(user=user)

        flavor_list = Products.objects.order_by('-type')
        context = {
            'flavor_list': flavor_list,
            'account': associated_account,
        }
        return render(request, 'drone_cones/home_page.html', context)

    @login_required
    def account_page(request):
        user = request.user
        associated_account = Account.objects.get(user=user)
        date_joined = user.date_joined.strftime("%m/%d/%Y")	

        order_list = Orders.objects.filter(account_id=associated_account.Id)

        context = {
            'account': associated_account,
            'first_name':associated_account.firstName, 
            'last_name':associated_account.lastName,
            'username':user.username, 
            'date_joined':date_joined,
            'address_1': associated_account.address,
            'address_2': associated_account.address2,
            'city': associated_account.city,
            'state': associated_account.state,
            'zip': associated_account.zip,
            'orderList': order_list}
            
        return render (request, 'drone_cones/account_page.html', context)

    @login_required
    def edit_account(request):

        user = request.user
        associated_account = Account.objects.get(user=user)

        if request.method == 'POST':
            form = EditAccountForm(request.POST)
            if form.is_valid():

                user_name = form.cleaned_data.get('username')
                first_name = form.cleaned_data.get('first_name')
                last_name = form.cleaned_data.get('last_name')

                if user.username != user_name:
                    try:
                        user.username = user_name
                        user.save()
                    except:
                        context = {'first_name':first_name, 'last_name':last_name, 'username':user_name, 'date_joined':user.date_joined.strftime("%m/%d/%Y"), 'account':associated_account, 'edit_taken_error': True}
                        print("THINGS WENT HAYWIRE")
                        return render(request, 'drone_cones/edit_account.html', context)
                
                associated_account.firstName = first_name
                associated_account.lastName = last_name

                associated_account.save()

                return HttpResponseRedirect("../account")                
        else:
            date_joined = user.date_joined.strftime("%m/%d/%Y")

            context = {'first_name':associated_account.firstName, 'last_name':associated_account.lastName, 'username':user.username, 'date_joined':date_joined, 'account':associated_account, 'edit_taken_error': False, 'taken_username': ""}

            return render (request, 'drone_cones/edit_account.html', context)

    @login_required
    def edit_address(request):

        user = request.user
        associated_account = Account.objects.get(user=user)


        if request.method == 'POST':
            form = EditAddressForm(request.POST)
            if form.is_valid():
                address_1 = form.cleaned_data.get('address_1')
                address_2 = form.cleaned_data.get('address_2')
                city = form.cleaned_data.get('city')
                state = form.cleaned_data.get('state')
                zip = form.cleaned_data.get('zip')

                associated_account.address = address_1
                associated_account.address2 = address_2
                associated_account.city = city
                associated_account.state = state
                associated_account.zip = zip

                associated_account.save()                
 
                return HttpResponseRedirect("../account")

        else:
            context = {
                'account': associated_account,
                'address_1': associated_account.address,
                'address_2': associated_account.address2,
                'city': associated_account.city,
                'state': associated_account.state,
                'zip': associated_account.zip
            }
            return render(request, 'drone_cones/edit_address.html', context)
            
class DroneView:
    @login_required
    def drone_dash(request):
        user = request.user
        associated_account = Account.objects.get(user=user)
        drone_list = associated_account.drone_set.all()

        context = {
            'account': associated_account,
            'drone_list': drone_list,
        }
        return render(request, 'drone_cones/drone_page.html', context)

    @login_required
    def drone_register(request):
        user = request.user
        associated_account = Account.objects.get(user=user)

drone_cones/templates/drone_cones/account_page.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Account Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'drone_cones/style.css' %}"/>
</head>

<body style="background-color: #008080">

    <div class="topnav">
        <a href="{% url 'drone_cones:home' %}"> <u>H</u>ome </a>
        <a href="{% url 'drone_cones:order' %}"> <u>O</u>rder </a>
        <a href="{% url 'drone_cones:drones' %}"> <u>D</u>rones </a>
        <a href="{% url 'drone_cones:account' %}"> <u>A</u>ccount </a>
            
        {% if account.is_admin %}
        <a href="{% url 'drone_cones:manager' %}"> <u>M</u>anager</a>
        {% endif %}
        <a href="/dronecones/logout">Logout</a>

	<a href="{% url 'drone_cones:account' %}">
        	<img class="baricon" src="{% static 'drone_cones/images/computer.png' %}" style="cursor: pointer" alt="computer">
        </a>
        <img class="peopleicon" src="{% static 'drone_cones/images/drone_cones_logo.png' %}"  alt="address book">
    </div>


    <div class="page-container">
        <div class="bar"> ACCOUNT </div>
        <div class="outer-border">
            <div class="inner-border">
                <div> Account Page </div>
                <div> ------------ </div>

                <div> Username: {{username}} </div>
                <div> First Name: {{first_name}} </div>
                <div> Last Name: {{last_name}}  </div>
                <div> Date Joined: {{date_joined}}  </div>
                <div style="margin-top: 5px; margin-bottom: 1em"></div>

                <div>
                    <a class="order" style="margin-left:0"  href="{% url 'drone_cones:edit_account' %}">EDIT</a>
                </div>
            </div>
        </div>

        <div class="outer-border">
            <div class="inner-border">
                <div> Shipping Info </div>
                <div> ------------  </div>

                <div> Address 1: {{address_1}} </div>
                <div> Address 2: {{address_2}} </div>
                <div> City:	 {{city}}      </div>
                <div> State:     {{state}}     </div>
                <div> ZIP:       {{zip}}       </div>
                <div style="margin-top: 5px; margin-bottom: 1em"></div>
                <div>
                    <a class="order" style="margin-left:0" href="{% url 'drone_cones:edit_address' %}">EDIT</a>
                </div>
            </div>
        </div>
	</div>

	<div class = "page-container">
		<div class="bar"> ORDER HISTORY </div>
        	<div class="outer-border">
		
			
                	{% for order in orderList %}
			<div class = "inner-border">
                    		<div class="dateOrdered">
                    	    		Date: {{ order.timeOrdered }}
                    		</div>
                    		<div class="cost">
                        		Cost: $ {{ order.orderCost }}
                    		</div>
                    		<div>
                        		<div class="orderHistoryScoops"> SCOOPS </div>
                        		{% if order.items.0.flavor1 or order.items.0.flavor2 %}
                                		<div class="orderItems">
                                        		<div class="orderItem" id="flavor1">
                                            			{{ order.items.0.flavor1 }}
                                        		</div>
                                       	 		<div class="orderItem" id="flavor2">
                                           			{{ order.items.0.flavor2 }}
                                        		</div>
                                		</div>
                        		{% else %}
                                		<div class="orderItems">
                                    			<div class="orderItem">
                                       			 	No scoops were selected
                                    			</div>
                                		</div>
                        		{% endif %}
				<div class="orderHistoryToppings"> TOPPINGS </div>
				{% if order.items.0.toppings.first or order.items.0.toppings.second or order.items.0.toppings.third %}
				    <div class="orderItems">
					<div class="orderItem" id="topping1">
					    {{ order.items.0.toppings.first }}
					</div>
					<div class="orderItem" id="topping2">
					    {{ order.items.0.toppings.second }}
					</div>
					<div class="orderItem" id="topping3">
					    {{ order.items.0.toppings.third }}
					</div>
				    </div>
				{% else %}
				<div class="orderItems">
				    <div class="orderItem">
					No toppings were selected
				    </div>
				</div>
				{% endif %}
				<div class="orderHistoryConeFlavors"> CONE FLAVORS </div>
				{% if order.items.0.cone %}
				    <div class="orderItems">
					<div class="orderItem" id="cone">
					    {{ order.items.0.cone }}
					</div>
				    </div>
				{% else %}
				<div class="orderItems">
				    <div class="orderItem">
					No cones were selected
				    </div>
				</div>
				{% endif %}
				<div class="spacer"></div>
			    </div>
			    </div>
			{% endfor %}
            		</div>
			</div>
        	</div>
</body>
</html>

drone_cones/templates/drone_cones/all_drones.html
{% load static %}

<DOCTYPE html>

	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<title>Admin Page</title>
		<link rel="stylesheet" type="text/css" href="{% static 'drone_cones/style.css' %}" />

	</head>


	<body>

		<div class="topnav">
			<a href="{% url 'drone_cones:home' %}"> <u>H</u>ome </a>
			<a href="{% url 'drone_cones:order' %}"> <u>O</u>rder </a>
			<a href="{% url 'drone_cones:drones' %}"> <u>D</u>rones </a>
			<a href="{% url 'drone_cones:account' %}"> <u>A</u>ccount </a>
			<a href="{% url 'drone_cones:manager' %}"> <u>M</u>anager</a>
			<a href="/dronecones/logout">Logout</a>

			<a href="{% url 'drone_cones:account' %}">
                                <img class="baricon" src="{% static 'drone_cones/images/computer.png' %}" style="cursor: pointer" alt="computer">
                        </a>
			<img class="peopleicon" src="{% static 'drone_cones/images/address_book_users.png' %}" alt="test">
		</div>

		<div class="topnav">
			<a href="{% url 'drone_cones:all_users' %}"> <u>U</u>sers </a>
			<a href="{% url 'drone_cones:stock' %}"> <u>S</u>tock </a>
			<a href="{% url 'drone_cones:finance' %}"> <u>F</u>inances </a>
			<a href="{% url 'drone_cones:all_drones' %}"> <u>D</u>rones </a>
		</div>

		<div class = "page-container">
			<div class = "outer-border">
                        {% for drone in drones %}

                                <div class="inner-border">

                                        <div>
                                                <h3> {{drone.droneName}} </h3>
                                                <p> {{drone.size}} </p>
                                                <div>
                                                        Is Active: <input type="checkbox" id="is_active" name="is_active" {% if drone.isActive %}checked{% endif %} disabled/>
                                                </div>

                                        </div>
                                        <div style="margin-top: 1em; margin-bottom:1em; user-select: none;">
                                                <a class="order" style="cursor: pointer; margin-left: 0" href="edit_drone/{{drone.id}}">EDIT</a>
                                                <a class="order" style="cursor: pointer; margin-left: 0" href="drone_breakdown/{{drone.id}}">INFO</a>
                                        </div>
                                </div>
                        {% endfor %}
                        </div>
		</div>

	</body>

	</html>

drone_cones/templates/drone_cones/create_account_page.html
{% load static %}

<DOCTYPE html>

<html lang="en">
	<head>
        	<meta charset="utf-8"/>
        	<title>Create Account Page</title>
		<link rel="stylesheet" type="text/css" href="{% static 'drone_cones/style.css' %}"/>

	</head>


	<body>
	
		<div class="topnav">
			<a><u>C</u>reate Account</a>
			<a href="{% url 'drone_cones:home' %}"><u>L</u>ogin</a>
		</div>

		<div class="page-container">
			<div class="outer-border">
			<div class="inner-border">
			{% block content %}
		
				<h2>Sign up</h2>
			
				<form method="post">
					{% csrf_token %}
			  		{% for field in form %}
						<p>
				  		{{ field.label_tag }}<br>
						{{ field }}
						{% if field.help_text %}
							<small style="color: grey">{{ field.help_text }}</small>
						{% endif %}
					  
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
						</p>
			  		{% endfor %}
			  
					<button type="submit">Sign up</button>
			 	</form>
		 	 {% endblock %}
			</div>
			</div>
		</div>
    </body>
</html>

drone_cones/templates/drone_cones/edit_user_manager.html
{% load static %}

<DOCTYPE html>

<html lang="en">
	<head>
        	<meta charset="utf-8"/>
        	<title>Account Page</title>
		<link rel="stylesheet" type="text/css" href="{% static 'drone_cones/style.css' %}"/>

	</head>

	<body>
	
		<div class="topnav">
            <a href="{% url 'drone_cones:home' %}"> <u>H</u>ome </a>
            <a href="{% url 'drone_cones:order' %}"> <u>O</u>rder </a>
            <a href="{% url 'drone_cones:drones' %}"> <u>D</u>rones </a>
			<a href="{% url 'drone_cones:account' %}"> <u>A</u>ccount </a>
			<a href="{% url 'drone_cones:manager' %}"> <u>M</u>anager</a>
			<a href="/dronecones/logout">Logout</a>

			<a href="{% url 'drone_cones:account' %}">
                                <img class="baricon" src="{% static 'drone_cones/images/computer.png' %}" style="cursor: pointer" alt="computer">
                        </a>

                        <img class="peopleicon" src="{% static 'drone_cones/images/address_book_users.png' %}" alt="test">
		</div>

		 <div class="topnav">
                        <a href="{% url 'drone_cones:all_users' %}"> <u>U</u>sers </a>
                        <a href="{% url 'drone_cones:stock' %}"> <u>S</u>tock </a>
                        <a href="{% url 'drone_cones:finance' %}"> <u>F</u>inances </a>
                        <a href="{% url 'drone_cones:all_drones' %}"> <u>D</u>rones </a>
                </div>

		<div class="page-container">
			<div class="bar"> ACCOUNT </div>
			<div class="outer-border">
				<div> Edit Account </div>
				<div> ------------ </div>
		

				<form action="{% url 'drone_cones:edit_user' account_id=id  %}" method = "post">

					{% csrf_token %}
					{{ form }}

					<div>	
						Username: <input id="Username" type="text" placeholder={{username}} name="username" maxlength = "100" value="{{username}}">  </input>
					</div>
					<div>
						First Name: <input id="First Name" type="text" name="first_name" maxlength="100" placeholder={{account.firstName}} value={{account.firstName}} required=True> </input>
					</div>
				
					<div>
						Last Name: <input id="Last Name" type="text" name="last_name" maxlength="100" placeholder={{account.lastName}} value={{account.lastName}} required=True> </input>
					</div>

					<div>
						Is Manager <input type="checkbox" id="is_manager" name="is_manager" {% if account.is_admin %}checked{% endif %}/>

					</div>

					<input type="submit" value="SAVE"/>
			</div>
		</div>
    </body>
</html>

drone_cones/templates/drone_cones/finance_page.html
{% load static %}

<DOCTYPE html>

	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<title>Finance Page</title>
		<link rel="stylesheet" type="text/css" href="{% static 'drone_cones/style.css' %}" />

	</head>


	<body>

		<div class="topnav">
			<a href="{% url 'drone_cones:home' %}"> <u>H</u>ome </a>
			<a href="{% url 'drone_cones:order' %}"> <u>O</u>rder </a>
			<a href="{% url 'drone_cones:drones' %}"> <u>D</u>rones </a>
			<a href="{% url 'drone_cones:account' %}"> <u>A</u>ccount </a>
			<a href="{% url 'drone_cones:manager' %}"> <u>M</u>anager</a>
			<a href="/dronecones/logout">Logout</a>

			<a href="{% url 'drone_cones:account' %}">
                                <img class="baricon" src="{% static 'drone_cones/images/computer.png' %}" style="cursor: pointer" alt="computer">
                        </a>

			<img class="peopleicon" src="{% static 'drone_cones/images/address_book_users.png' %}" alt="test">
		</div>

		<div class="topnav">
			<a href="{% url 'drone_cones:all_users' %}"> <u>U</u>sers </a>
			<a href="{% url 'drone_cones:stock' %}"> <u>S</u>tock </a>
			<a href="{% url 'drone_cones:finance' %}"> <u>F</u>inances </a>
			<a href="{% url 'drone_cones:all_drones' %}"> <u>D</u>rones </a>
		</div>


		<div class="page-container">
			<div class="bar">FINANCIAL PAGE</div>
			<div class="outer-border">
				<div class="inner-border">
					<div style="margin-bottom: 10px">
						<h2>Financial Information</h2>
						<h3>Gains</h3>
						<p>Total Revenue (Before Costs): ${{ total_revenue }}</p>
						<h3>Costs</h3>
						<p>Drone Owners: ${{ drone_owner_payout }}</p>
						<p>Inventory: ${{ inventory_cost }}</p>
						<h3>Net</h3>
						<p>Net Profit (After Costs): ${{ net_profit }}</p>
					</div>
				</div>
			</div>
		</div>
	</body>

	</html>

drone_cones/templates/drone_cones/manager_home.html
{% load static %}

<DOCTYPE html>

	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<title>Manager Page</title>
		<link rel="stylesheet" type="text/css" href="{% static 'drone_cones/style.css' %}" />

	</head>


	<body>

		<div class="topnav">
			<a href="{% url 'drone_cones:home' %}"> <u>H</u>ome </a>
			<a href="{% url 'drone_cones:order' %}"> <u>O</u>rder </a>
			<a href="{% url 'drone_cones:drones' %}"> <u>D</u>rones </a>
			<a href="{% url 'drone_cones:account' %}"> <u>A</u>ccount </a>
			<a href="{% url 'drone_cones:manager' %}"> <u>M</u>anager</a>
			<a href="/dronecones/logout">Logout</a>

			<a href="{% url 'drone_cones:account' %}">
                                <img class="baricon" src="{% static 'drone_cones/images/computer.png' %}" style="cursor: pointer" alt="computer">
                        </a>

			<img class="peopleicon" src="{% static 'drone_cones/images/address_book_users.png' %}" alt="test">
		</div>

		<div class="topnav">
			<a href="{% url 'drone_cones:all_users' %}"> <u>U</u>sers </a>
			<a href="{% url 'drone_cones:stock' %}"> <u>S</u>tock </a>
			<a href="{% url 'drone_cones:finance' %}"> <u>F</u>inances </a>
			<a href="{% url 'drone_cones:all_drones' %}"> <u>D</u>rones </a>
		</div>


		<div class="page-container">
			<div class="bar"> MANAGER DASHBOARD </div>
			<div class="row">
				<div class="column manager-left">
					<div> NUMBER OF USERS </div>
					<div class="managerNums">
						{{ userCount }}
					</div>
				</div>
				<div class="column manager-right">
					<div> NUMBER OF MANAGERS </div>
					<div class="managerNums">
						{{ managerCount }}
					</div>
				</div>
				<div class="column manager-right">
					<div> NUMBER OF ACTIVE DRONES </div>
					<div class="managerNums">
						{{ activeDroneCount }}
					</div>
				</div>
				<div class="column manager-left">
					<div> TOTAL REVENUE </div>
					<div class="managerNums">
						$ {{ totalRevenue }}
					</div>
				</div>
			</div>
		</div>
	</body>

	</html>